const notes = [
    {
        baseFrequency: 16.35,
        letter: "a",
        note: "C",
        type: 0,
        index : 0,
        placement : 0,
    },
    {
        baseFrequency: 17.32,
        letter: "w",
        note: "C#",
        type: 1,
        index : 1,
        placement : 1,
    },
    {
        baseFrequency: 18.35,
        letter: "s",
        note: "D",
        type: 0,
        index : 2,
        placement : 1,
    },
    {
        baseFrequency: 19.45,
        letter: "e",
        note: "Eb",
        type: 1,
        index : 3,
        placement : 2,
    },
    {
        baseFrequency: 20.60,
        letter: "d",
        note: "E",
        type: 0,
        index : 4,
        placement : 2,
    },
    {
        baseFrequency: 21.83,
        letter: "f",
        note: "F",
        type: 0,
        index : 5,
        placement : 3,
    },
    {
        baseFrequency: 23.12,
        letter: "t",
        note: "F#",
        type: 1,
        index : 6,
        placement : 4,
    },
    {
        baseFrequency: 24.50,
        letter: "g",
        note: "G", 
        type: 0,
        index : 7,
        placement : 4,
    }, 
    {
        baseFrequency: 25.96,
        letter: "y",
        note: "G#",
        type: 1,
        index : 8,
        placement : 5,
    }, 
    {
        baseFrequency: 27.50,
        letter: "h",
        note: "A", 
        type: 0,
        index : 9,
        placement : 5,
    }, 
    {
        baseFrequency: 29.14,
        letter: "u",
        note: "Bb",
        type: 1,
        index : 10,
        placement : 6,
    }, 
    {
        baseFrequency: 30.87,
        letter: "j",
        note: "B",
        type: 0,
        index : 11,
        placement : 6,
    }
]

export default notes;